<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ajinkyas-MacBook-Air.local" failures="3" tests="8" name="Test" time="5.271" errors="0" timestamp="2024-11-12T16:53:36 MST">
  <testcase classname="com.sep.Day2.GetData" name="testGetSingleRepository" time="2.6"/>
  <testcase classname="com.sep.Day2.GetData" name="testGetNonExistingRepository" time="0.398"/>
  <testcase classname="com.sep.Day2.GetData" name="testGetAllRepositories" time="0.918"/>
  <testcase classname="com.sep.Day2.GetData" name="testCreateRepository" time="0.513">
    <failure type="java.lang.AssertionError" message="Status code mismatch expected [201] but found [422]">
      <![CDATA[java.lang.AssertionError: Status code mismatch expected [201] but found [422]
at com.sep.Day2.GetData.testCreateRepository(GetData.java:96)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCreateRepository -->
  <testcase classname="com.sep.Day2.GetData" name="testCreateRepositoryWithExistingName" time="0.023">
    <failure type="java.lang.IllegalArgumentException" message="Cannot serialize because cannot determine how to serialize content-type text/plain; charset=ISO-8859-1">
      <![CDATA[java.lang.IllegalArgumentException: Cannot serialize because cannot determine how to serialize content-type text/plain; charset=ISO-8859-1
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.mapping.ObjectMapping.serialize(ObjectMapping.groovy:180)
at io.restassured.internal.mapping.ObjectMapping$serialize$1.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at io.restassured.internal.mapping.ObjectMapping$serialize$1.call(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.body(RequestSpecificationImpl.groovy:770)
at com.sep.Day2.GetData.testCreateRepositoryWithExistingName(GetData.java:117)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testCreateRepositoryWithExistingName -->
  <testcase classname="com.sep.Day2.GetData" name="testUpdateRepositoryName" time="0.0">
    <skipped/>
  </testcase> <!-- testUpdateRepositoryName -->
  <testcase classname="com.sep.Day2.GetData" name="testDeleteRepository" time="0.347">
    <failure type="java.lang.AssertionError" message="Expected status code 204 but received 404 expected [204] but found [404]">
      <![CDATA[java.lang.AssertionError: Expected status code 204 but received 404 expected [204] but found [404]
at com.sep.Day2.GetData.testDeleteRepository(GetData.java:168)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteRepository -->
  <testcase classname="com.sep.Day2.GetData" name="testDeleteNonExistingRepository" time="0.341"/>
</testsuite> <!-- Test -->
